### ISSUE TITLE
Unable to parse private key while generating public

### ISSUE THREAD

**Issue by browerjosiahdev** [gtg092x/gulp-sftp#50]
I am seeing the below error when I try to connect using the default private key (~/.ssh/id_rsa) with a passphrase. Any help or guidance would be much appreciated.

```
var gulp = require('gulp');
var sftp = require('gulp-sftp');

gulp.task('upload', function () {
    return (
      gulp.src('./www/*')
        .pipe(sftp({
          host: <-- host here -->,
          remotePath: 'www',
          passphrase: <-- passphrase here -->,
          user: 'root'
        }))
    );
});
```

```
Error: Unable to parse private key while generating public key (expected sequence)
    at Connection.connect (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/ssh2/lib/Connection.js:524:15)
    at Transform.pool (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/index.js:192:11)
    at Transform._transform (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/index.js:210:14)
    at Transform._read (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/gulp-sftp/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/josiahbrower/Documents/work/unibrowdev/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

**Comment by victorjeman** [comment]
I also have this problem
