### ISSUE TITLE
TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by Mangor** [gtg092x/gulp-sftp#57]
`[01:29:41] gulp-debug: dist/app
[01:29:41] gulp-debug: dist/assets
[01:29:41] gulp-debug: dist/favicon.ico
[01:29:41] Authenticating with password.
[01:29:41] gulp-debug: dist/index.html
[01:29:41] gulp-debug: 4 items
buffer.js:141
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:141:11)
    at new Buffer (buffer.js:62:10)
    at onNEWKEYS (/Users/user/project/node_modules/ssh2/lib/Connection.js:2366:29)
    at Parser.<anonymous> (/Users/user/project/node_modules/ssh2/lib/Connection.js:129:5)
    at emitNone (events.js:80:13)
    at Parser.emit (events.js:179:7)
    at Parser.parsePacket (/Users/user/project/node_modules/ssh2/lib/Parser.js:468:12)
    at Parser.execute (/Users/user/project/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/Users/user/project/node_modules/ssh2/lib/Connection.js:536:18)
    at emitOne (events.js:90:13)`

**Comment by derozn** [comment]
+1

**Comment by talymo** [comment]
Same issue

**Comment by Rairomero** [comment]
Same issue
