### ISSUE TITLE
Is this project abandoned??

### ISSUE THREAD

**Issue by phawxby** [gtg092x/gulp-sftp#67]
8 pull requests waiting, 26 issues with little activity and no major code updates in over a year!

If the author needs support managing the project how about giving a few more people access to the repo?

Side note: I came here because gulp-sftp isn't gulp 4 compatible 

```
TypeError: dest.on is not a function
    at Transform.Readable.pipe (/home/ubuntu/xerox-framework/node_modules/gulp-sftp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at /home/ubuntu/xerox-framework/gulpfile.js:338:18
    at /home/ubuntu/xerox-framework/node_modules/gulp-git/lib/push.js:30:5
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by gtg092x** [comment]
Yeah I need help with this. Want to be an admin?

**Comment by phawxby** [comment]
I can help out. Considering the amount of people that use this module it would be good if there were a few people able to assist.

**Comment by valaxy** [comment]
The project is still useful, just need some update which upgrades `ssh2`

**Comment by phawxby** [comment]
@valaxy is that an offer to help out too?

**Comment by valaxy** [comment]
@phawxby I'm afraid I dont't have enough knowledge about ssh to help out. :)

But I could report issues. :)
