### ISSUE TITLE
issue with connection

### ISSUE THREAD

**Issue by naymaeu** [gtg092x/gulp-sftp#70]
Hi I have a problem with connection

Got always this kind of issue:

```
Authenticating with private key.
events.js:160
      throw er; // Unhandled 'error' event

Error: No such file
    at SFTP._parse (/node_modules/ssh2/lib/SFTP/SFTPv3.js:1090:23)
    at ChannelStream.<anonymous> (/node_modules/ssh2/lib/SFTP/SFTPv3.js:72:10)
    at emitOne (events.js:96:13)
    at ChannelStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ChannelStream.Readable.push (_stream_readable.js:134:10)

```

Any idea what is wrong with that. I use SFTP on Transmit app and working fine. Keys are working well via terminal SSH conection.

**Comment by kig-rob** [comment]
Having this issue as well. Were you able to solve?

**Comment by thomasfrobieter** [comment]
Same here
